opt_passes_str = "annotation2metdadata forceattrs inferattrs coro-early lower-expect simplifycfg sroa early-cse callsite-splitting openmp-opt ipsccp called-value-propagation globalopt typepromotion argpromotion instcombine aggressive-instcombine always-inline inliner-wrapper wholeprogramdevirt module-inline inline rpo-function-attrs openmp-opt-cgscc speculative-execution jump-threading correlated-propagation libcalls-shrinkwrap tailcallelim reassociate constraint-elimination loop-simplify lcssa loop-instsimplify loop-simplifycfg licm loop-rotate simple-loop-unswitch loop-idiom indvars loop-deletion loop-unroll-full vector-combine mldst-motion gvn sccp bdce adce memcpyopt dse move-auto-init coro-elide coro-split coro-cleanup deadargelim  elim-avail-extern recompute-globalsaa float2int lower-constant-intrinsics chr loop-distribute inject-tli-mappings loop-vectorize infer-alignment loop-load-elim slp-vectorizer loop-unroll alignment-from-assumptions loop-sink instsimplify div-rem-pairs constmerge cg-profile rel-lookup-table-converter annotation-remarks verify"
old_passes_str = "correlated-propagation scalarrepl lowerinvoke strip strip-nondebug sccp globalopt gvn jump-threading globaldce loop-unswitch scalarrepl-ssa loop-reduce break-crit-edges loop-deletion reassociate lcssa codegenprepare memcpyopt functionattrs loop-idiom lowerswitch constmerge loop-rotate partial-inliner inline early-cse indvars adce loop-simplify instcombine simplifycfg dse loop-unroll lower-expect tailcallelim licm sink mem2reg prune-eh functionattrs ipsccp deadargelim sroa loweratomic terminate"

new = list(opt_passes_str.split())
old = list(old_passes_str.split())

add = [i for i in new if i in old]

'''
DIFFERENT PASSES:
['annotation2metdadata', 'forceattrs', 'inferattrs', 'coro-early', 'callsite-splitting', 'openmp-opt', 'called-value-propagation', 'typepromotion', 'argpromotion', 'aggressive-instcombine', 'always-inline', 'inliner-wrapper', 'wholeprogramdevirt', 'module-inline', 'rpo-function-attrs', 'openmp-opt-cgscc', 'speculative-execution', 'libcalls-shrinkwrap', 'constraint-elimination', 'loop-instsimplify', 'loop-simplifycfg', 'simple-loop-unswitch', 'loop-unroll-full', 'vector-combine', 'mldst-motion', 'bdce', 'move-auto-init', 'coro-elide', 'coro-split', 'coro-cleanup', 'elim-avail-extern', 'recompute-globalsaa', 'float2int', 'lower-constant-intrinsics', 'chr', 'loop-distribute', 'inject-tli-mappings', 'loop-vectorize', 'infer-alignment', 'loop-load-elim', 'slp-vectorizer', 'alignment-from-assumptions', 'loop-sink', 'instsimplify', 'div-rem-pairs', 'cg-profile', 'rel-lookup-table-converter', 'annotation-remarks', 'verify']
COMMON PASSES:
['lower-expect', 'simplifycfg', 'sroa', 'early-cse', 'ipsccp', 'globalopt', 'instcombine', 'inline', 'jump-threading', 'correlated-propagation', 'tailcallelim', 'reassociate', 'loop-simplify', 'lcssa', 'licm', 'loop-rotate', 'loop-idiom', 'indvars', 'loop-deletion', 'gvn', 'sccp', 'adce', 'memcpyopt', 'dse', 'deadargelim', 'loop-unroll', 'constmerge']
'''